// Fantasy & Medieval RPG Equipment, Weapons, Armor, and Magic Types
// This module provides lists and enums for use in item generation, loot tables, and name generators.

#[derive(Debug, Clone)]
pub enum WeaponType {
    Sword,
    Axe,
    Mace,
    Dagger,
    Spear,
    Halberd,
    Bow,
    Crossbow,
    Staff,
    Wand,
    Flail,
    Scythe,
    Sling,
    Club,
    Warhammer,
    Rapier,
    Greatsword,
    Longsword,
    Shortsword,
    Katana,
    Whip,
    ThrowingKnife,
    Chakram,
    Polearm,
    Trident,
    Morningstar,
    Lance,
    Javelin,
    Scepter,
    Unarmed,
}

#[derive(Debug, Clone)]
pub enum ArmorType {
    Cloth,
    Leather,
    StuddedLeather,
    Chainmail,
    ScaleMail,
    SplintMail,
    Plate,
    Brigandine,
    Robe,
    Gambeson,
    Shield,
    Buckler,
    TowerShield,
    Helmet,
    Circlet,
    Gauntlets,
    Greaves,
    Boots,
    Cloak,
    Mantle,
    Bracers,
    Pauldrons,
    Cuirass,
    Vambraces,
    Gorget,
}

#[derive(Debug, Clone)]
pub enum EquipmentSlot {
    MainHand,
    OffHand,
    Head,
    Chest,
    Legs,
    Feet,
    Hands,
    Shoulders,
    Back,
    Waist,
    Neck,
    Finger,
    Trinket,
}

#[derive(Debug, Clone)]
pub enum MagicSchool {
    Fire,
    Water,
    Air,
    Earth,
    Light,
    Shadow,
    Arcane,
    Nature,
    Ice,
    Lightning,
    Blood,
    Necromancy,
    Holy,
    Illusion,
    Enchantment,
    Transmutation,
    Divination,
    Conjuration,
    Abjuration,
    Summoning,
    Curse,
    Rune,
    Psionic,
}

#[derive(Debug, Clone)]
pub enum ItemType {
    Weapon(WeaponType),
    Armor(ArmorType),
    Consumable,
    Potion,
    Scroll,
    Food,
    Drink,
    Tool,
    Key,
    Gem,
    Ring,
    Amulet,
    Relic,
    Artifact,
    Ingredient,
    Material,
    Quest,
    Treasure,
    Book,
    Map,
    Misc,
}

pub const FANTASY_EQUIPMENT_NAMES: &[&str] = &[
    // Weapons
    "Dragonslayer",
    "Frostbrand",
    "Shadowfang",
    "Sunblade",
    "Stormcaller",
    "Doomhammer",
    "Moonblade",
    "Bloodletter",
    "Soulreaver",
    "Thunderstrike",
    // Armor
    "Celestial Plate",
    "Shadow Cloak",
    "Ironbark Shield",
    "Phoenix Helm",
    "Wyrmscale Mail",
    "Mantle of the Magi",
    "Boots of Swiftness",
    "Gauntlets of Ogre Power",
    "Crown of Insight",
    "Bracers of Defense",
    // Misc
    "Ring of Invisibility",
    "Amulet of Protection",
    "Orb of Annihilation",
    "Staff of the Archmage",
    "Tome of Forgotten Lore",
    "Potion of Healing",
    "Elixir of Mana",
    "Scroll of Fireball",
    "Gem of True Seeing",
    "Key of the Ancients",
];

// Example: Generate a random equipment name by combining type, magic school, and fantasy name
// let name = format!("{} {} of {}", rarity, weapon_type, magic_school);
